### ISSUE TITLE
[BUG] Callback URL is http rather than https

### ISSUE THREAD

**Issue by arcoast** [jordan-dalby/ByteStash#110]
**Describe the bug**
I'm attempting to setup bytestash with Authelia and getting an error which I think is secondary to a problem with the callback URL.

`bytestash.yml`
```yaml
services:
    bytestash:
        image: ghcr.io/jordan-dalby/bytestash:latest
        container_name: bytestash
        networks:
            - traefik
        # ports:
        #     - 5000:5000
        environment:
            - BASE_PATH=${BYTESTASH_BASE_PATH}
            - JWT_SECRET=${BYTESTASH_JWT_SECRET}
            - TOKEN_EXPIRY=${BYTESTASH_TOKEN_EXPIRY}
            - ALLOW_NEW_ACCOUNTS=${BYTESTASH_ALLOW_NEW_ACCOUNTS}
            - DEBUG=${BYTESTASH_DEBUG}
            - OIDC_ENABLED=${BYTESTASH_OIDC_ENABLED}
            - OIDC_DISPLAY_NAME=${BYTESTASH_OIDC_DISPLAY_NAME}
            - OIDC_ISSUER_URL=${BYTESTASH_OIDC_ISSUER_URL}
            - OIDC_CLIENT_ID=${BYTESTASH_OIDC_CLIENT_ID}
            - OIDC_CLIENT_SECRET=${BYTESTASH_OIDC_CLIENT_SECRET}
            # - OIDC_SCOPES=${BYTESTASH_OIDC_SCOPES}
        volumes:
            - ${CONFIG}/bytestash/bytestash:/data/snippets
        restart: unless-stopped
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=traefik"
            - "traefik.http.services.bytestash.loadbalancer.server.port=5000"
            - "traefik.http.routers.bytestash.entrypoints=websecure"
            - "traefik.http.routers.bytestash.rule=Host(`bytestash.${DOMAIN}`)"
            - "traefik.http.routers.bytestash.middlewares=authelia@file, securityHeaders@file"
 ```
My `.env` file
```
BYTESTASH_BASE_PATH=
BYTESTASH_JWT_SECRET=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
BYTESTASH_TOKEN_EXPIRY=24h
BYTESTASH_ALLOW_NEW_ACCOUNTS=true
BYTESTASH_DEBUG=true
BYTESTASH_OIDC_ENABLED=true
BYTESTASH_OIDC_DISPLAY_NAME=Authelia
BYTESTASH_OIDC_ISSUER_URL=https://authelia.DOMAIN.COM
BYTESTASH_OIDC_CLIENT_ID=bytestash
BYTESTASH_OIDC_CLIENT_SECRET=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

Relevant snippet of my Authelia config
```yaml
      - client_id: bytestash #done
        client_name: Bytestash
        client_secret: {{ secret "/config/secrets/CLIENT_SECRET_BYTESTASH" }}
        public: false
        authorization_policy: bytestash
        consent_mode: implicit
        scopes:
          - openid
          - groups
          - email
          - profile
        redirect_uris:
          - https://bytestash.{{ env "DOMAIN" }}/api/auth/oidc/callback
        userinfo_signed_response_alg: none
```

Logs
```
2024-11-22T23:01:32.852075878Z [DEBUG] Database initialization completed successfully
2024-11-22T23:01:32.854961314Z [INFO] Server running on port 5000
2024-11-22T23:02:30.466270451Z [DEBUG] Discovering OIDC configuration from https://authelia.DOMAIN.COM/
2024-11-22T23:02:30.559818199Z [DEBUG] Discovery successful
2024-11-22T23:02:30.559950114Z [DEBUG] Discovered issuer: https://authelia.DOMAIN.COM
2024-11-22T23:02:30.560009867Z [DEBUG] OIDC client configured successfully
2024-11-22T23:02:30.560093911Z [DEBUG] SELECT COUNT(*) as count FROM users
2024-11-22T23:02:30.560596749Z [DEBUG] Full callback URL: http://bytestash.DOMAIN.COM/api/auth/oidc/callback
2024-11-22T23:02:30.561855094Z [DEBUG] Handling callback with: {
2024-11-22T23:02:30.561861383Z   currentUrl: 'http://bytestash.DOMAIN.COM/api/auth/oidc/callback',
2024-11-22T23:02:30.561863221Z   callbackUrl: 'http://bytestash.DOMAIN.COM/api/auth/oidc/callback'
2024-11-22T23:02:30.561864752Z }
2024-11-22T23:02:30.562423501Z [ERROR] OIDC callback error: Error: Invalid or expired state parameter
2024-11-22T23:02:30.562433412Z     at OIDCConfig.handleCallback (file:///app/src/oidc/oidcConfig.js:134:13)
2024-11-22T23:02:30.562435154Z     at file:///app/src/routes/oidcRoutes.js:65:40
2024-11-22T23:02:30.562436638Z     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-11-22T23:02:31.764193216Z [DEBUG] SELECT COUNT(*) as count FROM users
2024-11-22T23:02:34.843227619Z [DEBUG] Generated auth URL: URL {
2024-11-22T23:02:34.843250092Z   href: 'https://authelia.DOMAIN.COM/api/oidc/authorization?redirect_uri=http%3A%2F%2Fbytestash.DOMAIN.COM%2Fapi%2Fauth%2Foidc%2Fcallback&scope=openid+profile+email&state=8onauKXUrZZ675QjkN05GLgTbNOKeR9xxNXrC0rhjZg&nonce=34moAEnVHPj35Q5RQkrOneuGne_fIjjKzcz8zN49o1s&response_type=code&client_id=bytestash&code_challenge=eHGHdXNC7S7nKZHUPcXAqCPT4wt4Zv4dQcm5NpzLrjE&code_challenge_method=S256',
2024-11-22T23:02:34.843258775Z   origin: 'https://authelia.DOMAIN.COM',
2024-11-22T23:02:34.843260850Z   protocol: 'https:',
2024-11-22T23:02:34.843262376Z   username: '',
2024-11-22T23:02:34.843263785Z   password: '',
2024-11-22T23:02:34.843265162Z   host: 'authelia.DOMAIN.COM',
2024-11-22T23:02:34.843266697Z   hostname: 'authelia.DOMAIN.COM',
2024-11-22T23:02:34.843268138Z   port: '',
2024-11-22T23:02:34.843269519Z   pathname: '/api/oidc/authorization',
2024-11-22T23:02:34.843270986Z   search: '?redirect_uri=http%3A%2F%2Fbytestash.DOMAIN.COM%2Fapi%2Fauth%2Foidc%2Fcallback&scope=openid+profile+email&state=8onauKXUrZZ675QjkN05GLgTbNOKeR9xxNXrC0rhjZg&nonce=34moAEnVHPj35Q5RQkrOneuGne_fIjjKzcz8zN49o1s&response_type=code&client_id=bytestash&code_challenge=eHGHdXNC7S7nKZHUPcXAqCPT4wt4Zv4dQcm5NpzLrjE&code_challenge_method=S256',
2024-11-22T23:02:34.843273073Z   searchParams: URLSearchParams {
2024-11-22T23:02:34.843274728Z     'redirect_uri' => 'http://bytestash.DOMAIN.COM/api/auth/oidc/callback',
2024-11-22T23:02:34.843276298Z     'scope' => 'openid profile email',
2024-11-22T23:02:34.843277771Z     'state' => '8onauKXUrZZ675QjkN05GLgTbNOKeR9xxNXrC0rhjZg',
2024-11-22T23:02:34.843279346Z     'nonce' => '34moAEnVHPj35Q5RQkrOneuGne_fIjjKzcz8zN49o1s',
2024-11-22T23:02:34.843280830Z     'response_type' => 'code',
2024-11-22T23:02:34.843282325Z     'client_id' => 'bytestash',
2024-11-22T23:02:34.843283826Z     'code_challenge' => 'eHGHdXNC7S7nKZHUPcXAqCPT4wt4Zv4dQcm5NpzLrjE',
2024-11-22T23:02:34.843285428Z     'code_challenge_method' => 'S256' },
2024-11-22T23:02:34.843286890Z   hash: ''
2024-11-22T23:02:34.843288267Z }
2024-11-22T23:05:36.282155968Z [DEBUG] SELECT COUNT(*) as count FROM users
2024-11-22T23:05:36.282371154Z [DEBUG] Full callback URL: http://bytestash.DOMAIN.COM/api/auth/oidc/callback?code=authelia_ac_HjIJ26Ne_YdMsFFBjgdHhQ1rRypLNpQD57pxvshv8xM.WzJzgK4Lpb58f8ynGQi4bVUDfZrBdx3vuaKKZny5QV0&iss=https%3A%2F%2Fauthelia.DOMAIN.COM&scope=openid+profile+email+groups&state=A7jUGDoB2wOclZ4fEFJkLgkpTm4FKUo4gTpjQrNqrV4
2024-11-22T23:05:36.282503707Z [DEBUG] Handling callback with: {
2024-11-22T23:05:36.282510055Z   currentUrl: 'http://bytestash.DOMAIN.COM/api/auth/oidc/callback?code=authelia_ac_HjIJ26Ne_YdMsFFBjgdHhQ1rRypLNpQD57pxvshv8xM.WzJzgK4Lpb58f8ynGQi4bVUDfZrBdx3vuaKKZny5QV0&iss=https%3A%2F%2Fauthelia.DOMAIN.COM&scope=openid+profile+email+groups&state=A7jUGDoB2wOclZ4fEFJkLgkpTm4FKUo4gTpjQrNqrV4',
2024-11-22T23:05:36.282512727Z   callbackUrl: 'http://bytestash.DOMAIN.COM/api/auth/oidc/callback'
```

I can get to the Bytestash homepage and get the above error logs when attempting to sign in with Authelia.   I've noticed that the callbackUrl is `http` despite my Authelia config being configured as `https`

```json
{
  "error": "invalid_request",
  "error_description": "The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. The 'redirect_uri' parameter does not match any of the OAuth 2.0 Client's pre-registered 'redirect_uris'."
}
```

Happy to do any further troubleshooting and contribute to the wiki once I get Authelia up and working to help improve the docs.

**Comment by jordan-dalby** [comment]
Hm yeah looks like ByteStash is forcing http in this case, I'll have a look, let me know if you make any developments in the meantime.

**Comment by jordan-dalby** [comment]
Looks like it's http, so this might be normal behaviour, it'll just redirect you back to whatever URL you're coming from, change to http in Authelia config or enable https in your reverse proxy for ByteStash :)

**Comment by arcoast** [comment]
Thanks for looking, my Bytestash instance is running on https with Traefik, so it's really unusual that the referrer URL is being picked up as http. (Took me a while to spot it) 

I don't run http at all and have no http entrypoint setup in Traefik.

So, realistically, unless there's a way to configure this in Bytestash I suspect this issue is going to crop up again in the future with others.

I guess I could set up a new entrypoint for http in Traefik and make a permanent http to https redirection, and open a new port forward on Opnsense but it feels excessive to have to do so due to this.

**Comment by jordan-dalby** [comment]
@arcoast 
Yeah don't do that, this is a ByteStash issue- looking into it.

**Comment by jordan-dalby** [comment]
@arcoast 
Fixed, mind giving it a go for me? bytestash-dev:pr-111

**Comment by arcoast** [comment]
Can confirm this fixes the issue and Authelia is working fine.

I'll write it up and submit the docs once I've got my kids bathed and dressed. 

Thanks for the quick fix!

**Comment by jordan-dalby** [comment]
@arcoast 
Awesome thanks!
